Repository Students-of-the-city-of-Kostroma/trpo_automation, pull requests merged in 2020-04, with the labels that each got.

#239 Создание класса для проверки лаб по паттерну Стратегия
  README.md
  TRPO/.gitignore
  TRPO/TRPO.pro
  TRPO/main.cpp
  TRPO/strategylab.cpp
  TRPO/strategylab.h
  TRPO/tcpserver.cpp
  TRPO/tcpserver.h
Labels: Coding

#240 Изменение структуры проекта
  LR/07/.gitignore
  LR/07/07.pro
  LR/07/TCPServer/TCPServer.pro
  LR/07/TCPServer/main.cpp
  LR/07/TCPServer/strategylab.cpp
  LR/07/TCPServer/strategylab.h
  LR/07/TCPServer/tcpserver.cpp
  LR/07/TCPServer/tcpserver.h
  LR/07/Tests/Tests.pro
Labels: Server

#243 Изменения структуры проекта
  LR/07/07.pro
  LR/07/TCPServer/TCPServer.pro
  LR/07/TCPServer/strategylab.cpp
  LR/07/TCPServer/strategylab.h
  LR/07/TCPServer/tcpserver.h
  LR/07/Tests/Tests.pro
  LR/07/Tests/tst_temp.cpp
  LR/07/src/main.cpp
  LR/07/src/src.pro
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
  TRPO/.gitignore
  TRPO/main.cpp
  TRPO/tcpserver.cpp
Labels: Coding

#245 Создан класс для Функционала
  LR/07/src/functional.cpp
  LR/07/src/functional.h
  LR/07/src/src.pro
Labels: Coding

#246 Юнит тесты методов tcp-сервера
  LR/07/Tests/Tests.pro
  LR/07/Tests/test_tcp.cpp
  LR/07/Tests/test_tcp.h
  LR/07/Tests/tst_temp.cpp
Labels: Server, Testing

#247 Реализовал поиск ссылки на код и номера лабы
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding

#231 Delete AddMarkTest.py
  email/18-ISbo-2a/AddMarkTest.py
Labels: Sprint 5, Testing

#235 Попытка исправить ошибку(можно ли сравнивать с None? Если нет, то почему?
  email/18-ISbo-2a/APIgoogle.py
Labels: Google, Sprint 5, bug

#252 Release changing
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/base_WorkWithLetters.py
  email/18-ISbo-2b/config.py
  email/18-ISbo-2b/global_AnswersForUsers.py
  email/18-ISbo-2b/global_Letter.py
  email/18-ISbo-2b/global_LetterResult.py
  email/18-ISbo-2b/global_Timer.py
  email/18-ISbo-2b/global_User.py
  email/18-ISbo-2b/google_CheckEmail.py
  email/18-ISbo-2b/instructions.txt
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/moderate_FormAnswers.py
  email/18-ISbo-2b/reserve_Reserve.py
  email/18-ISbo-2b/send_InformUsers.py
  email/18-ISbo-2b/send_SetResults.py
Labels: release

#267 Added logging
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/main.py
Labels: Loging, Sprint 5

#265 Добавили поиск координат для выставления оценки в Google таблицу
  email/18-ISbo-2a/group.py
  email/18-ISbo-2a/poisk.py
Labels: Google

#268 Был доработан main.py
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/config.py
  email/18-ISbo-2a/main.py
Labels: Client, Sprint 5

#274 Прототип конфига
  LR/07/config/.answerStructure
Labels: Coding

#280 Подключение функционала проверки кода
  LR/07/src/config/answerStructure.xml
  LR/07/src/src.pro
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding

#296 Issue 160 selenium and server
  LR03/Repository.xml
  LR03/pom.xml
  LR03/src/main/java/Selenium.java
  LR03/src/main/java/Server.java
Labels: Selenium

#295 Issue 111
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/base_WorkWithLetters.py
  email/18-ISbo-2b/config.py
  email/18-ISbo-2b/global_AnswersForUsers.py
  email/18-ISbo-2b/global_Letter.py
  email/18-ISbo-2b/global_LetterResult.py
  email/18-ISbo-2b/global_Timer.py
  email/18-ISbo-2b/global_User.py
  email/18-ISbo-2b/google_CheckEmail.py
  email/18-ISbo-2b/instructions.txt
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/moderate_FormAnswers.py
  email/18-ISbo-2b/reserve_Reserve.py
  email/18-ISbo-2b/send_InformUsers.py
  email/18-ISbo-2b/send_SetResults.py
Labels: Sprint 2, Sprint 3, Sprint 5, Sprint 6, realization

#302 Bug Fixed
  LR03/Repository.xml
  LR03/src/main/java/Selenium.java
  LR03/src/main/java/Server.java
Labels: Selenium, bug

#276 Исправил баги.
  email/18-ISbo-2a/APIgoogle.py
Labels: Sprint 6, bug

#301 настроил парсинг json данных
  LR/07/src/functional.cpp
  LR/07/src/functional.h
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding

#313 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: Sprint 6

#320 Добавил логи на APIgoogle.py
  email/18-ISbo-2a/APIgoogle.py
Labels: Loging, Sprint 6

#306 Обновлен метод Check_Issues()
  LR03/src/main/java/Selenium.java
  LR03/src/main/java/Server.java
Labels: Selenium

#311 Реализован функционал отправки ответа клиенту
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding, Server

#283 Декодер конфигов, новые автотесты
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Decode.py
  email/18-ISbo-2a/Example.json.bak
  email/18-ISbo-2a/Test_google.py
  email/18-ISbo-2a/Test_google_sheet_search_group.py
  email/18-ISbo-2a/Test_validation.py
  email/18-ISbo-2a/Validation.py
  email/18-ISbo-2a/config.py
  email/18-ISbo-2a/config.py.bak
Labels: Sprint 5, Sprint 6, Testing

#331 Переписал код в связи с изменениями спецификации JSON
  email/18-ISbo-2b/Base/TCP/SendJSONForCheck.py
  email/18-ISbo-2b/Base/TCP/config1.txt
  email/18-ISbo-2b/Base/TCP/config2.txt
  email/18-ISbo-2b/Base/TCP/config3.txt
  email/18-ISbo-2b/Base/TCP/config4.txt
  email/18-ISbo-2b/Base/TCP/config5.txt
  email/18-ISbo-2b/Base/TCP/configServ.txt
  email/18-ISbo-2b/Base/TCP/global_Letter.py
  email/18-ISbo-2b/Base/TCP/global_LetterResult.py
  email/18-ISbo-2b/Base/TCP/global_User.py
  email/18-ISbo-2b/Base/TCP/klient.py
  email/18-ISbo-2b/Base/TCP/server1.py
  email/18-ISbo-2b/Base/TCP/server2.py
  email/18-ISbo-2b/Base/TCP/server3.py
  email/18-ISbo-2b/Base/TCP/server4.py
  email/18-ISbo-2b/Base/TCP/server5.py
  email/18-ISbo-2b/base_WorkWithLetters.py
Labels: Sprint 5, Sprint 6, add functional, bug, main, realization

#332 Merge + issue-111
  README.md
  email/18-ISbo-2b/base_WorkWithLetters.py
Labels: Sprint 5, add functional

#323 Создание экземпляров класса Letter #322
  email/18-ISbo-2b/global_ExOfLetters.py
Labels: Sprint 6, Testing

#310 Доработка тестов и редактирование под стандарты оформления
  LR/07/Tests/TestTcp.cpp
  LR/07/Tests/TestTcp.h
  LR/07/Tests/Tests.pro
  LR/07/Tests/test_tcp.cpp
Labels: Server, Testing

#334 Fix bug in calls ind imports
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/send_InformUsers.py
Labels: Sprint 5, bug

#341 Проблема соединения с Github
  LR/07/src/functional.cpp
  LR/07/src/functional.h
  LR/07/src/resources.qrc
  LR/07/src/src.pro
  LR/07/src/tcpserver.cpp
Labels: bug

#349 Создание Gateway
  LR/07/src/config/jsonSpecificationForClientRequest.xml
  LR/07/src/gateway.cpp
  LR/07/src/gateway.h
  LR/07/src/resources.qrc
  LR/07/src/src.pro
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding, add functional

#374 обработка данных на сервере
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding

#375 Подключил инициализацию объектов StrategyLab и Functional в конструкт…
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding

#387 Проведен рефакторинг APIgoogle и добавлен файл с шаблонами
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/pattern.py
Labels: Google, Sprint 7, documentation, v.0.0.0.4

#381 Переписан слот отправки ответа клиенту.
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding, Server

#388 Проведен рефакторинг методов в APIgoogle
  email/18-ISbo-2a/APIgoogle.py
Labels: Sprint 7, documentation, v.0.0.0.4

#396 Рефакторинг кода в APIgoogle.py
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Validation.py
  email/18-ISbo-2a/pattern.py
Labels: Google, Sprint 7, v.0.0.0.4

#397 Добавление непрерывного чтения писем.
  .gitignore
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/client.py
  email/18-ISbo-2a/main.py
Labels: realization, v.0.0.0.4

#333 Merge + issue-260
  .gitignore
  README.md
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/base_WorkWithLetters.py
  email/18-ISbo-2b/config.py
  email/18-ISbo-2b/global_AnswersForUsers.py
  email/18-ISbo-2b/global_Letter.py
  email/18-ISbo-2b/global_LetterResult.py
  email/18-ISbo-2b/global_Timer.py
  email/18-ISbo-2b/global_User.py
  email/18-ISbo-2b/google_CheckEmail.py
  email/18-ISbo-2b/google_ValidateRules.py
  email/18-ISbo-2b/instructions.txt
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/moderate_FormAnswers.py
  email/18-ISbo-2b/reserve_Reserve.py
  email/18-ISbo-2b/send_InformUsers.py
  email/18-ISbo-2b/send_SetResults.py
  mail/Google/CheckEmail.py
  mail/Google/Gmail/Gmail.py
  mail/Google/Gmail/config.py
  mail/Google/Tables/Auth.py
  mail/Google/Tables/Sheet.py
  mail/Google/Validation/.gitkeep
  mail/Google/Validation/Validation.py
  mail/Google/Validation/ValidationLetters/Test_Mails.py
  mail/Google/Validation/ValidationLetters/bodys.txt
  mail/Google/Validation/ValidationLetters/subjects.txt
  mail/Google/Validation/__init__.py
  mail/Google/Validation/mail_module.py
  mail/Google/Validation/main.py
Labels: Sprint 5, add functional

#404 Добавление функционала для отправки сообщений
  email/18-ISbo-2b/google_CheckEmail.py
  mail/Google/CheckEmail.py
  mail/Google/Gmail/Gmail.py
  mail/Google/Gmail/config.py
  mail/Google/Tables/Auth.py
  mail/Google/Tables/Sheet.py
  mail/Google/Validation/.gitkeep
  mail/Google/Validation/Letter.py
  mail/Google/Validation/User.py
  mail/Google/Validation/Validation.py
  mail/Google/Validation/ValidationLetters/Test_Mails.py
  mail/Google/Validation/ValidationLetters/bodys.txt
  mail/Google/Validation/ValidationLetters/main.py
  mail/Google/Validation/ValidationLetters/subjects.txt
  mail/Google/Validation/__init__.py
  mail/Google/Validation/mail_module.py
  mail/Google/Validation/main.py
Labels: Sprint 5, Sprint 6, add functional, main, realization

#344 Добавление функционала для чтения писем с почты.
  email/18-ISbo-2b/google_CheckEmail.py
  mail/Google/CheckEmail.py
  mail/Google/Gmail/Gmail.py
  mail/Google/Gmail/config.py
  mail/Google/Tables/Auth.py
  mail/Google/Tables/Sheet.py
  mail/Google/Validation/.gitkeep
  mail/Google/Validation/Letter.py
  mail/Google/Validation/User.py
  mail/Google/Validation/Validation.py
  mail/Google/Validation/ValidationLetters/Test_Mails.py
  mail/Google/Validation/ValidationLetters/bodys.txt
  mail/Google/Validation/ValidationLetters/main.py
  mail/Google/Validation/ValidationLetters/subjects.txt
  mail/Google/Validation/__init__.py
  mail/Google/Validation/mail_module.py
  mail/Google/Validation/main.py
Labels: Sprint 5, Sprint 6, add functional, main, realization

#405 Добавление функционала для отправки сообщений.
  email/18-ISbo-2b/send_InformUsers.py
Labels: Sprint 6, add functional, main, realization, stucture

#406 Добавление функционала парсинга данных с github
  .gitignore
  email/18-ISbo-2b/base_WorkWithLetters.py
  email/18-ISbo-2b/global_ExOfLetters.py
  email/18-ISbo-2b/google_CheckEmail.py
  email/18-ISbo-2b/google_ValidateRules.py
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/send_InformUsers.py
Labels: Sprint 6, add functional, main, realization

#348 Добавлено логирование в тестовый модуль
  README.md
  email/18-ISbo-2b/DelAfteImplemLoging/TestLoging/Proba.txt
  email/18-ISbo-2b/DelAfteImplemLoging/TestLoging/test.py
  email/18-ISbo-2b/DelAfteImplemLoging/logs.py
  email/18-ISbo-2b/DelAfteImplemLoging/test.py
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/base_WorkWithLetters.py
  email/18-ISbo-2b/config.py
  email/18-ISbo-2b/global_AnswersForUsers.py
  email/18-ISbo-2b/global_ExOfLetters.py
  email/18-ISbo-2b/global_Letter.py
  email/18-ISbo-2b/global_LetterResult.py
  email/18-ISbo-2b/global_Timer.py
  email/18-ISbo-2b/global_User.py
  email/18-ISbo-2b/google_CheckEmail.py
  email/18-ISbo-2b/instructions.txt
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/moderate_FormAnswers.py
  email/18-ISbo-2b/reserve_Reserve.py
  email/18-ISbo-2b/send_InformUsers.py
  email/18-ISbo-2b/send_SetResults.py
Labels: Loging, Sprint 5, realization

#407 Удаление временных папок Base
  email/18-ISbo-2b/Base/Server/HTTPReq.py
  email/18-ISbo-2b/Base/Server/JSONSend.py
  email/18-ISbo-2b/Base/Server/Serv/__init__.py
  email/18-ISbo-2b/Base/Server/Server.py
  email/18-ISbo-2b/Base/Server/cgi-bin/hello.py
  email/18-ISbo-2b/Base/TCP/README.md
  email/18-ISbo-2b/Base/TCP/SendJSONForCheck.py
  email/18-ISbo-2b/Base/TCP/config1.txt
  email/18-ISbo-2b/Base/TCP/config2.txt
  email/18-ISbo-2b/Base/TCP/config3.txt
  email/18-ISbo-2b/Base/TCP/config4.txt
  email/18-ISbo-2b/Base/TCP/config5.txt
  email/18-ISbo-2b/Base/TCP/configServ.txt
  email/18-ISbo-2b/Base/TCP/global_Letter.py
  email/18-ISbo-2b/Base/TCP/global_LetterResult.py
  email/18-ISbo-2b/Base/TCP/global_User.py
  email/18-ISbo-2b/Base/TCP/klient.py
  email/18-ISbo-2b/Base/TCP/server1.py
  email/18-ISbo-2b/Base/TCP/server2.py
  email/18-ISbo-2b/Base/TCP/server3.py
  email/18-ISbo-2b/Base/TCP/server4.py
  email/18-ISbo-2b/Base/TCP/server5.py
  email/18-ISbo-2b/Base/TCP/student1.json
  email/18-ISbo-2b/Base/TCP/student2.json
  email/18-ISbo-2b/Base/TCP/student3.json
  email/18-ISbo-2b/Base/TCP/student4.json
  email/18-ISbo-2b/Base/TCP/student5.json
  email/18-ISbo-2b/tmp/LettersConvertToString.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/SendJSONForCheck.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/config1.txt
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/config2.txt
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/config3.txt
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/config4.txt
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/config5.txt
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/configServ.txt
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/config_port.json
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/global_Letter.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/global_LetterResult.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/global_User.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/klient.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/server1.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/server2.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/server3.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/server4.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/server5.py
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/student1.json
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/student2.json
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/student3.json
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/student4.json
  email/18-ISbo-2b/tmp/Work SendJSONForCheck/student5.json
  email/18-ISbo-2b/tmp/base_WorkWithLetters.py
  email/18-ISbo-2b/tmp/global_Letter.py
  email/18-ISbo-2b/tmp/global_User.py
Labels: stucture

#415 Добавлен .dat файл для unit-test отчетов
  LR/07/Tests/test.dat
Labels: Server, Testing

#416 добавил отправку ответа клиенту (результаты проверки лабы)
  LR/07/src/gateway.cpp
  LR/07/src/gateway.h
  LR/07/src/tcpserver.cpp
Labels: Coding

#419 допилил gateway
  LR/07/src/config/jsonSpecificationForClientRequest.xml
  LR/07/src/gateway.cpp
  LR/07/src/gateway.h
Labels: Coding

#409 Получение ссылки на файл .cpp
  LR/07/src/functional.cpp
  LR/07/src/functional.h
Labels: Coding

#417 Реализовано получение листинга кода с GitHub
  LR/07/src/functional.cpp
  LR/07/src/functional.h
Labels: Coding

#421 Упс, статический сигнал - в нем вся проблема
  LR/07/src/functional.cpp
  LR/07/src/gateway.cpp
  LR/07/src/gateway.h
  LR/07/src/tcpserver.cpp
Labels: bug

#377 Реализован класс тестов для проверки ЛР3
  LR/03/Repository.xml
  LR/03/pom.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/test/java/SeleniumTest.java
  LR03/pom.xml
Labels: Coding

#422 Исправил slotReadingDataJson()
  LR/07/src/tcpserver.cpp
Labels: Coding

#429 Реализация функционала формирования Letter.
  email/18-ISbo-2b/google_CheckEmail.py
Labels: Sprint 5, Sprint 6, Sprint 7, add functional, main, realization

#432 Фикс метода.
  email/18-ISbo-2b/google_CheckEmail.py
Labels: Sprint 7, bug, main

#424 Подключен xml конфиг
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
Labels: Coding

#425 Unit-тесты для метода LetterConvertToString()
  email/18-ISbo-2b/unit_tests/LettersConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_LetterConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_LetterConvertToString_py.xml
Labels: Sprint 6, Sprint 7, Testing

#431 Доработка метода LettersConvertToString() #428
  email/18-ISbo-2b/base_WorkWithLetters.py
Labels: Coding, Sprint 7, bug

#435 Update azure-pipelines.yml
  azure-pipelines.yml
Labels: Sprint 7

#463 started strategy lab
  LR/07/src/gateway.cpp
  LR/07/src/gateway.h
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
  LR/07/src/tcpserver.cpp
Labels: Coding

#457 Исправил метод paringJson
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
Labels: Coding

#456 Issue 395
  LR/07/src/functional.cpp
  LR/07/src/functional.h
Labels: Coding

#465 Добавил тесты,исправил протокол передачи данных
  LR/03/Repository.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/test/java/SeleniumTest.java
  LR/03/src/test/java/ServerTest.java
Labels: Coding, Server, Testing

#466 Update azure-pipelines.yml
  azure-pipelines.yml
Labels: Sprint 7

#467 Update azure-pipelines.yml
  azure-pipelines.yml
Labels: Sprint 7

#470 исправлен баг с битыми xpath
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/test/java/SeleniumTest.java
Labels: bug

#472 18-VTbo-1b LR03
  .travis.yml
  LR/03/Repository.xml
  LR/03/pom.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/test/java/SeleniumTest.java
  LR/03/src/test/java/ServerTest.java
Labels: Selenium

#473 Релиз 0.0.0.6
  .gitignore
  LICENSE
  README.md
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/base_WorkWithLetters.py
  email/18-ISbo-2b/config_Mail.py
  email/18-ISbo-2b/config_Port.json
  email/18-ISbo-2b/config_Project.py
  email/18-ISbo-2b/config_Server.txt
  email/18-ISbo-2b/global_AnswersForUsers.py
  email/18-ISbo-2b/global_Letter.py
  email/18-ISbo-2b/global_LetterResult.py
  email/18-ISbo-2b/global_Timer.py
  email/18-ISbo-2b/global_User.py
  email/18-ISbo-2b/google_Auth.py
  email/18-ISbo-2b/google_CheckEmail.py
  email/18-ISbo-2b/google_Sheet.py
  email/18-ISbo-2b/google_ValidateRules.py
  email/18-ISbo-2b/instructions.txt
  email/18-ISbo-2b/logs/.gitkeep
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/main_1_google_CheckEmail.py
  email/18-ISbo-2b/main_2_base_WorkWithLetters.py
  email/18-ISbo-2b/main_3_send_SetResults.py
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
  email/18-ISbo-2b/main_5_send_InformUsers.py
  email/18-ISbo-2b/moderate_FormAnswers.py
  email/18-ISbo-2b/moderate_PatternsOfLetter.py
  email/18-ISbo-2b/reserve_Reserve.py
  email/18-ISbo-2b/send_SetResults.py
Labels: release

#468 Донастройка интеграции
  azure-pipelines.yml
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/pattern.py
  email/18-ISbo-2a/test_google.py
  email/18-ISbo-2a/test_google_search_tablic.py
  email/18-ISbo-2a/test_google_sheet_search_group.py
  email/18-ISbo-2a/test_validation.py
Labels: Sprint 8

#399 Added logging of input parameters
  email/18-ISbo-2a/log_method.py
Labels: Loging, Sprint 7

#477 PublishBuildArtifacts
  azure-pipelines.yml
Labels: Sprint 8

#401 Added more detailed logging main.py
  email/18-ISbo-2a/main.py
Labels: Loging, Sprint 7

#482 Added crypt_file and decrypt_file methods
  email/18-ISbo-2a/crypto.py
Labels: Sprint 8

#483 Исправлен метод search_group
  email/18-ISbo-2a/APIgoogle.py
Labels: bug, v.0.0.0.5
