Repository Students-of-the-city-of-Kostroma/trpo_automation, pull requests merged in 2020-06, with the labels that each got.

#141 Оптимизация функций парсинга принятых сообщений
  email/18-ISbo-2b/main_1_CheckEmail.py
  email/18-ISbo-2b/work_EmailLibrary.py
Labels: Coding, Sprint 11, add functional, realization, refactoring

#150 Update README.md
  README.md
Labels: documentation

#138 Добавление студента в журнал
  email/18-ISbo-2b/work_Sheet.py
Labels: Sprint 11, add functional

#131 Исправил баг
  email/18-ISbo-2b/main_4_FormAnswers.py
Labels: Sprint 11, bug, v.0.0.0.8

#149 Failed 7 & 8 тесты валидации
  email/18-ISbo-2b/main_1_CheckEmail.py
  email/18-ISbo-2b/work_ValidateRules.py
Labels: Sprint 11, bug, v.0.0.0.6

#120 Баг в файле main_2_WorkWithLetters в методе LettersConvertToString() с полем Body #119
  email/18-ISbo-2b/main_2_WorkWithLetters.py
Labels: Sprint 11, bug, v.0.0.0.6

#144 Обновил файл конфигурации CL
  .travis.yml
  .travis/18-VTbo-1a.yml
  .travis/18-VTbo-1b.yml
  .travis/dev.yml
Labels: Sprint 6, documentation

#148 Конфиг для dev
  .travis.yml
  .travis/18-VTbo-1b.yml
  .travis/dev.yml
  LR/03/Repository.xml
Labels: Sprint 6, documentation

#153 Доработка логирования
  email/18-ISbo-2b/logs/global_logging.py
  email/18-ISbo-2b/logs/log_config.py
  email/18-ISbo-2b/logs/logfiles/log1[пример].txt
  email/18-ISbo-2b/main_1_CheckEmail.py
  email/18-ISbo-2b/work_ValidateRules.py
Labels: Sprint 11, add functional, v.0.0.0.6

#159 Переделал метод на считывание из файла labs.xml
  LR/03/Labs3_url.xml
  LR/03/labs.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/main/java/ServerSomthing.java
Labels: Coding, Sprint 6

#161 Попытка покрыть логами класс StrategyLab
  LR/07/src/main.cpp
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
Labels: Coding

#165 Написание unit-теста на покрытие сценария test_S_4_t6 #164
  email/18-ISbo-2b/unit_tests/unittest_LettersConvertToString.py
Labels: Sprint 12, Testing, v.0.0.0.8

#187 Внедрение системы reject кодов
  LR/07/src/tcpserver.cpp
  LR/07/src/utils/gateway.cpp
  LR/07/src/utils/gateway.h
  LR/07/src/utils/internalexception.h
Labels: Coding

#199 Рефакторинг, добавление теста, переработка функции MakeAnswersForUser…
  __init__.py
  email/18-ISbo-2b/main_2_WorkWithLetters.py
  email/18-ISbo-2b/main_4_FormAnswers.py
  email/18-ISbo-2b/unit_tests/unittest_CheckUsers.py
  email/18-ISbo-2b/unit_tests/unittest_LettersConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_MakeAnswersForUsers.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_SendLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SetMarks.py
  email/18-ISbo-2b/work_PatternsOfLetter.py
  email/__init__.py
Labels: Coding, Sprint 12, СРОЧНО

#156 Исправлен bug при обращении к pattern.py
  email/18-ISbo-2a/mainp/Example.json.bin
  email/18-ISbo-2a/mainp/config.py
  email/18-ISbo-2a/mainp/config.py.bin
  email/18-ISbo-2a/mainp/credentials.json.bin
  email/18-ISbo-2a/mainp/pattern.py
  email/18-ISbo-2a/mainp/token.pickle.bin
Labels: bug, v.0.0.0.7

#189 fix import logging_config
  email/18-ISbo-2a/mainp/log_method.py
  email/18-ISbo-2a/mainp/logging_config.conf
  email/18-ISbo-2a/mainp/logging_config.py
Labels: Sprint 11

#202 Hotfixs.
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Validation.py
  email/18-ISbo-2a/__init__.py
  email/18-ISbo-2a/client.py
  email/18-ISbo-2a/configs/Example.json.bin
  email/18-ISbo-2a/configs/__init__.py
  email/18-ISbo-2a/configs/config.py
  email/18-ISbo-2a/configs/config.py.bin
  email/18-ISbo-2a/configs/credentials.json.bin
  email/18-ISbo-2a/configs/token.pickle.bin
  email/18-ISbo-2a/main.py
  email/18-ISbo-2a/mainp/Example.json.bin
  email/18-ISbo-2a/mainp/config.py.bin
  email/18-ISbo-2a/mainp/credentials.json.bin
  email/18-ISbo-2a/mainp/token.pickle.bin
  email/18-ISbo-2a/pattern.py
  email/18-ISbo-2a/requirements.txt
  email/18-ISbo-2a/stub_for_server.py
  email/18-ISbo-2a/tests/test_google.py
  email/18-ISbo-2a/tests/test_google_search_tablic.py
  email/18-ISbo-2a/tests/test_validation.py
  email/18-ISbo-2a/utils/__init__.py
  email/18-ISbo-2a/utils/crypto.py
  email/18-ISbo-2a/utils/log_method.py
  email/18-ISbo-2a/utils/logging_config.py
Labels: wontfix

#194 Переместил файл портов в корень
  LR/03/src/main/java/Server.java
  labs.xml
Labels: Coding, Sprint 6

#203 автоматизация автотестирования по сценариям
  .gitignore
  LR/07/src/resources.qrc
  LR/07/src/utils/internalexception.cpp
  LR/07/tests/getTestSuites/credentials.json
  LR/07/tests/getTestSuites/downloadTestSuites.sh
  LR/07/tests/getTestSuites/googleDrive.py
  LR/07/tests/getTestSuites/token.pickle
  LR/07/tests/testgateway.cpp
  LR/07/tests/testgateway.h
Labels: Coding, Testing

#201 Разделение проверок родителя и наследников
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
  LR/07/src/tcpserver.cpp
Labels: Coding

#205 update configs
  .travis.yml
  .travis/18-VTbo-1a.yml
  .travis/18-VTbo-1b.yml
  .travis/dev.yml
  LR/07/src/strategylab.cpp
  LR/07/tests/getTestSuites/downloadTestSuites.sh
  LR/07/tests/getTestSuites/googleDrive.py
  LR/07/tests/getTestSuites/token.pickle
Labels: Coding

#195 Изменение валидации
  email/18-ISbo-2a/Validation.py
  email/18-ISbo-2a/pattern.py
Labels: Sprint 11, refactoring

#207 подготовка проекта к пре-релизу
  LR/07/src/components/functional.cpp
  LR/07/src/components/functional.h
  LR/07/src/components/strategylab.cpp
  LR/07/src/components/strategylab.h
  LR/07/src/components/tcpserver.cpp
  LR/07/src/components/tcpserver.h
  LR/07/src/config/answerStructure.xml
  LR/07/src/main.cpp
  LR/07/src/src.pro
  LR/07/src/utils/logfile.cpp
  LR/07/src/utils/logfile.h
Labels: Coding

#219 Поправки конфилктов и работы тестов.
  .gitignore
  .travis.yml
  .travis/18-ISbo-2a.yml
  .travis/18-VTbo-1a.yml
  .travis/18-VTbo-1b.yml
  .travis/dev.yml
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Validation.py
  email/18-ISbo-2a/configs/Example.json.bin
  email/18-ISbo-2a/configs/config.py
  email/18-ISbo-2a/configs/config.py.bin
  email/18-ISbo-2a/configs/credentials.json.bin
  email/18-ISbo-2a/configs/token.pickle
  email/18-ISbo-2a/configs/token.pickle.bin
  email/18-ISbo-2a/main.py
  email/18-ISbo-2a/stub_for_server.py
  email/18-ISbo-2a/tests/test_google.py
  email/18-ISbo-2a/tests/test_google_search_tablic.py
  email/18-ISbo-2a/tests/test_google_sheet_search_group.py
  email/18-ISbo-2a/tests/test_validation.py
  email/18-ISbo-2a/token.pickle
  email/18-ISbo-2a/utils/crypto.py
Labels: main

#221 интеграция с клиентом
  LR/07/src/resources.qrc
  LR/07/tests/getTestSuites/googleDrive.py
  LR/07/tests/getTestSuites/token.pickle
  LR/07/tests/testgateway.cpp
Labels: Sprint 10, Testing, refactoring

#220 Убрал приветственное сообщение
  LR/07/src/components/tcpserver.cpp
Labels: Coding

#230 Чтение из общего конфига лаб
  email/18-ISbo-2b/labs.xml
  email/18-ISbo-2b/main_2_WorkWithLetters.py
Labels: Coding, Sprint 12, СРОЧНО

#228 Добавлено Логирование
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/main/java/ServerSomthing.java
  LR/03/src/test/java/ServerAndSeleniumTest.java
  LR/03/src/test/java/ServerTest.java
Labels: Sprint 6

#232 Рефакторинг юнит-тестов, тестирование логирования и релиза v.0.0.0.8
  email/18-ISbo-2b/config_Project.py
  email/18-ISbo-2b/unit_tests/__init__.py
  email/18-ISbo-2b/unit_tests/unittest_CheckUsers.py
  email/18-ISbo-2b/unit_tests/unittest_FormAnswersForUser.py
  email/18-ISbo-2b/unit_tests/unittest_FormJSONDates.py
  email/18-ISbo-2b/unit_tests/unittest_FormListWithLetters.py
  email/18-ISbo-2b/unit_tests/unittest_LettersConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_MakeAnswersForUsers.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_SendLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SetMarks.py
  email/18-ISbo-2b/unit_tests/unittest_Validate_Letters.py
Labels: Epic, Sprint 12, Testing, v.0.0.0.8

#237 Прод нового пре-релиза 18-ISbo-2b -> dev (сливание изменений в рабочую ветку)
  .gitignore
  .travis.yml
  .travis/18-VTbo-1a.yml
  .travis/18-VTbo-1b.yml
  .travis/dev.yml
  LR/03/Repository.xml
  LR/03/pom.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/main/java/ServerSomthing.java
  LR/03/src/test/java/SeleniumTest.java
  LR/03/src/test/java/ServerTest.java
  LR/07/.gitignore
  LR/07/07.pro
  LR/07/src/components/functional.cpp
  LR/07/src/components/functional.h
  LR/07/src/components/strategylab.cpp
  LR/07/src/components/strategylab.h
  LR/07/src/components/tcpserver.cpp
  LR/07/src/components/tcpserver.h
  LR/07/src/config/answerStructure.xml
  LR/07/src/config/jsonSpecificationForClientRequest.xml
  LR/07/src/main.cpp
  LR/07/src/resources.qrc
  LR/07/src/src.pro
  LR/07/src/utils/gateway.cpp
  LR/07/src/utils/gateway.h
  LR/07/src/utils/internalexception.cpp
  LR/07/src/utils/internalexception.h
  LR/07/src/utils/logfile.cpp
  LR/07/src/utils/logfile.h
  LR/07/tests/getTestSuites/credentials.json
  LR/07/tests/getTestSuites/downloadTestSuites.sh
  LR/07/tests/getTestSuites/googleDrive.py
  LR/07/tests/getTestSuites/token.pickle
  LR/07/tests/test.dat
  LR/07/tests/testgateway.cpp
  LR/07/tests/testgateway.h
  LR/07/tests/tests.pro
  README.md
  azure-pipelines.yml
  email/18-ISbo-2b/requirements.txt
  labs.xml
Labels: Pre-Release, Sprint 12, add functional, main, refactoring

#236 Прод нового пре-релиза 18-ISbo-2b -> dev
  .gitignore
  README.md
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/c_config
  email/18-ISbo-2b/c_config2
  email/18-ISbo-2b/c_json
  email/18-ISbo-2b/c_token
  email/18-ISbo-2b/config_Project.py
  email/18-ISbo-2b/global_Logging.py
  email/18-ISbo-2b/labs.xml
  email/18-ISbo-2b/logfiles/log2020.6.8-15.37.txt
  email/18-ISbo-2b/logfiles/log2020.6.8-15.38.txt
  email/18-ISbo-2b/logfiles/log2020.6.8-16.19.txt
  email/18-ISbo-2b/logfiles/log2020.6.8-16.20.txt
  email/18-ISbo-2b/logfiles/log2020.6.8-16.21.txt
  email/18-ISbo-2b/logfiles/log2020.6.8-16.22.txt
  email/18-ISbo-2b/logfiles/log2020.6.8-16.23.txt
  email/18-ISbo-2b/logs/.gitkeep
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/main_1_CheckEmail.py
  email/18-ISbo-2b/main_2_WorkWithLetters.py
  email/18-ISbo-2b/main_3_SetResults.py
  email/18-ISbo-2b/main_4_FormAnswers.py
  email/18-ISbo-2b/main_5_InformUsers.py
  email/18-ISbo-2b/requirements.txt
  email/18-ISbo-2b/unit_tests/__init__.py
  email/18-ISbo-2b/unit_tests/unittest_CheckUsers.py
  email/18-ISbo-2b/unit_tests/unittest_FormAnswersForUser.py
  email/18-ISbo-2b/unit_tests/unittest_FormJSONDates.py
  email/18-ISbo-2b/unit_tests/unittest_FormListWithLetters.py
  email/18-ISbo-2b/unit_tests/unittest_LettersConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_MakeAnswersForUsers.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_SendLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SetMarks.py
  email/18-ISbo-2b/unit_tests/unittest_Validate_Letters.py
  email/18-ISbo-2b/work_Auth.py
  email/18-ISbo-2b/work_EmailLibrary.py
  email/18-ISbo-2b/work_Loger.py
  email/18-ISbo-2b/work_PatternsOfLetter.py
  email/18-ISbo-2b/work_Sheet.py
  email/18-ISbo-2b/work_ValidateRules.py
Labels: Pre-Release, Sprint 12, add functional, refactoring

#246 Добавил обработчик на отсутсвие main функции, привел код к стандартам
  LR/07/src/components/functional.cpp
  LR/07/src/components/strategylab.cpp
Labels: bug

#235 Исправление стилистики кода
  LR/07/src/components/strategylab.cpp
  LR/07/src/utils/logfile.cpp
Labels: Coding, Sprint 10

#245 Подготовка к pre-release
  .travis/18-VTbo-1a.yml
  .travis/dev.yml
  LR/03/Labs3_url.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/main/java/ServerSomthing.java
  LR/03/src/test/java/SeleniumTest.java
  LR/03/src/test/java/ServerAndSeleniumTest.java
  LR/03/src/test/java/ServerTest.java
Labels: Sprint 6

#277 Логирование проекта, всюду, достигаем отметки в 100%
  LR/07/src/components/functional.cpp
  LR/07/src/components/functional.h
  LR/07/src/components/strategylab.cpp
  LR/07/src/main.cpp
Labels: Coding
