Repository Students-of-the-city-of-Kostroma/trpo_automation, pull requests merged in 2020-05, with the labels that each got.

#30 Правка бага #27
  email/18-ISbo-2b/main_1_google_CheckEmail.py
Labels: bug

#32 правка бага #31
  email/18-ISbo-2b/main_2_base_WorkWithLetters.py
Labels: bug

#33 правки импортов #15
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/main_1_google_CheckEmail.py
  email/18-ISbo-2b/main_2_base_WorkWithLetters.py
  email/18-ISbo-2b/main_3_send_SetResults.py
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
  email/18-ISbo-2b/main_5_send_InformUsers.py
Labels: Coding, realization

#48 Написаны unittest'ы на функцию SendJSONForCheck(), найден и исправлен баг
  email/18-ISbo-2b/main_2_base_WorkWithLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck_py.xml
Labels: Sprint 10, Testing

#54 Написаны юниттесты на функцию MakeAnswersForUser
  email/18-ISbo-2b/unit_tests/unittest_FormAnswersForUser.py
Labels: Sprint 10, Testing

#49 Написаны юнниттесты на функцию Validate_Letters()
  email/18-ISbo-2b/unit_tests/unittest_Validate_Letters.py
  email/18-ISbo-2b/unit_tests/unittest_Validate_Letters_py.xml
Labels: Sprint 10, Testing, documentation

#53 Дополнил метод
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
  email/18-ISbo-2b/moderate_PatternsOfLetter.py
Labels: Sprint 10, add functional, realization

#75 Подправлены баги в проекте
  email/18-ISbo-2b/config_Project.py
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
  email/18-ISbo-2b/moderate_PatternsOfLetter.py
Labels: bug, v.0.0.0.6

#73 Update main_4_moderate_FormAnswers.py
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
Labels: bug

#76 Написаны юнит тесты на функцию CheckUsers()
  email/18-ISbo-2b/unit_tests/unittest_CheckUsers.py
  email/18-ISbo-2b/unit_tests/unittest_CheckUsers_py.xml
Labels: Sprint 10, Testing, documentation

#77 Исправил баг в методе ValidateLetters
  email/18-ISbo-2b/google_ValidateRules.py
  email/18-ISbo-2b/main_1_google_CheckEmail.py
Labels: Sprint 10, bug, v.0.0.0.6

#74 Внесение правок в юниттесты метода AnswersForUser
  email/18-ISbo-2b/unit_tests/unittest_FormAnswersForUser.py
Labels: Sprint 10, Testing, v.0.0.0.6

#82 Обновление файла для работы с таблицами #81
  email/18-ISbo-2b/google_Sheet.py
Labels: Coding, Critical, Sprint 10, v.0.0.0.6

#85 Добавление unit-теста на функцию SendLetters
  email/18-ISbo-2b/global_AnswersForUsers.py
  email/18-ISbo-2b/main_5_send_InformUsers.py
  email/18-ISbo-2b/unit_tests/unittest_SendLetters.py
Labels: Sprint 10, Testing, documentation

#78 Исправить баг в файле main_2_base_WorkWithLetters #10
  email/18-ISbo-2b/log2.txt
  email/18-ISbo-2b/main_2_base_WorkWithLetters.py
Labels: Sprint 10, bug, v.0.0.0.6, СРОЧНО

#95 Написаны юнит тесты на функцию FormJSONDates
  email/18-ISbo-2b/unit_tests/unittest_FormJSONDates.py
  email/18-ISbo-2b/unit_tests/unittest_FormJSONDates_py.xml
Labels: Coding, Sprint 11, Story, Testing

#80 Дописал тесты GW
  LR/07/tests/testgateway.cpp
Labels: Testing

#103 Issue 570
  LR/03/pom.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/main/java/ServerSomthing.java
Labels: Coding

#96 Исправления для состыковки с клиентом группы ИС
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/main/java/ServerSomthing.java
  LR/03/src/test/java/SeleniumTest.java
  LR/03/src/test/java/ServerTest.java
Labels: Coding

#100 Реализация логирования
  LR/07/src/logfile.cpp
  LR/07/src/logfile.h
  LR/07/src/src.pro
Labels: Coding, Sprint 8

#102 Восстановление проверки Context
  LR/07/src/strategylab.cpp
Labels: Coding, Sprint 8

#99 Тесты на SetMarks и пара опечаток(исправленных)
  email/18-ISbo-2b/google_ValidateRules.py
  email/18-ISbo-2b/main_3_send_SetResults.py
  email/18-ISbo-2b/unit_tests/unittest_SetMarks.py
Labels: Sprint 11, Testing, v.0.0.0.6

#108 Написаны юнит тесты на функцию MakeAnswersForUsers()
  email/18-ISbo-2b/unit_tests/unittest_MakeAnswersForUsers.py
  email/18-ISbo-2b/unit_tests/unittest_MakeAnswersForUsers_py.xml
Labels: Coding, Sprint 11, Story, Testing

#110 Выкат релиза
  .gitignore
  README.md
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/config_Project.py
  email/18-ISbo-2b/global_ExOfLetters.py
  email/18-ISbo-2b/global_Timer.py
  email/18-ISbo-2b/instructions.txt
  email/18-ISbo-2b/log2.txt
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/main_1_CheckEmail.py
  email/18-ISbo-2b/main_2_WorkWithLetters.py
  email/18-ISbo-2b/main_3_SetResults.py
  email/18-ISbo-2b/main_4_FormAnswers.py
  email/18-ISbo-2b/main_5_InformUsers.py
  email/18-ISbo-2b/reserve_Reserve.py
  email/18-ISbo-2b/unit_tests/unittest_FormAnswersForUser.py
  email/18-ISbo-2b/unit_tests/unittest_FormJSONDates.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/LettersConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/TestSendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/Work SendJSONForCheck/__init__.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/Work SendJSONForCheck/base_WorkWithLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/Work SendJSONForCheck/send_SetResults.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/__init__.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/base_WorkWithLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config1.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config2.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config3.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config4.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config5.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/configServ.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config_port.json
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/data.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/global_Letter.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/global_LetterResult.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/global_User.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/instructionsFor_unittest_SendJSONForCheck.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/send_SetResults.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server1.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server2.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server3.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server4.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server5.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_Validate_Letters.py
  email/18-ISbo-2b/work_Auth.py
  email/18-ISbo-2b/work_Loger.py
  email/18-ISbo-2b/work_PatternsOfLetter.py
  email/18-ISbo-2b/work_Sheet.py
  email/18-ISbo-2b/work_ValidateRules.py
Labels: Coding, Sprint 11, main, realization, refactoring

#112 Выкат наполовину протестированного релиза в dev
  .gitignore
  README.md
  email/18-ISbo-2b/__init__.py
  email/18-ISbo-2b/config_Project.py
  email/18-ISbo-2b/global_ExOfLetters.py
  email/18-ISbo-2b/global_Timer.py
  email/18-ISbo-2b/instructions.txt
  email/18-ISbo-2b/log2.txt
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/main_1_CheckEmail.py
  email/18-ISbo-2b/main_2_WorkWithLetters.py
  email/18-ISbo-2b/main_3_SetResults.py
  email/18-ISbo-2b/main_4_FormAnswers.py
  email/18-ISbo-2b/main_5_InformUsers.py
  email/18-ISbo-2b/reserve_Reserve.py
  email/18-ISbo-2b/unit_tests/unittest_FormAnswersForUser.py
  email/18-ISbo-2b/unit_tests/unittest_FormJSONDates.py
  email/18-ISbo-2b/unit_tests/unittest_FormJSONDates_py.xml
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/LettersConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/TestSendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/Work SendJSONForCheck/__init__.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/Work SendJSONForCheck/base_WorkWithLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/Work SendJSONForCheck/send_SetResults.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/__init__.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/base_WorkWithLetters.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config1.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config2.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config3.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config4.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config5.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/configServ.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/config_port.json
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/data.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/global_Letter.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/global_LetterResult.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/global_User.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/instructionsFor_unittest_SendJSONForCheck.txt
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/send_SetResults.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server1.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server2.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server3.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server4.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck()/server5.py
  email/18-ISbo-2b/unit_tests/unittest_SendJSONForCheck.py
  email/18-ISbo-2b/unit_tests/unittest_SetMarks.py
  email/18-ISbo-2b/unit_tests/unittest_Validate_Letters.py
  email/18-ISbo-2b/work_Auth.py
  email/18-ISbo-2b/work_Loger.py
  email/18-ISbo-2b/work_PatternsOfLetter.py
  email/18-ISbo-2b/work_Sheet.py
  email/18-ISbo-2b/work_ValidateRules.py
Labels: Coding, Sprint 11, main, realization, refactoring

#114 Merge Добавление ЛР03 в ветку dev
  .travis.yml
  .travis/18-VTbo-1b.yml
  LR/03/pom.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/main/java/ServerSomthing.java
  LR/03/src/test/java/SeleniumTest.java
  LR/03/src/test/java/ServerTest.java
Labels: Coding, Sprint 5

#116 Проверки на main функцию
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
Labels: Coding

#117 Исправил баг
  email/18-ISbo-2b/work_PatternsOfLetter.py
Labels: bug, v.0.0.0.6, СРОЧНО

#118 Unittest'ы на функцию LettersConvertToString() #90
  __init__.py
  email/18-ISbo-2b/unit_tests/__init__.py
  email/18-ISbo-2b/unit_tests/unittest_LetterConvertToString.py
  email/18-ISbo-2b/unit_tests/unittest_LetterConvertToString_py.xml
  email/18-ISbo-2b/unit_tests/unittest_LettersConvertToString.py
  email/__init__.py
Labels: Sprint 11, Testing, v.0.0.0.6

#125 Добавил комментарии
  email/18-ISbo-2a/Validation.py
  email/18-ISbo-2a/log_method.py
  email/18-ISbo-2a/pattern.py
Labels: Sprint 10

#70 Поправил методы на основе новой таблицы.
  email/18-ISbo-2a/APIgoogle.py
Labels: Sprint 10

#122 Список лабораторных работ и их номера в теме письма
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Example.json.bin
  email/18-ISbo-2a/config.py.bin
  email/18-ISbo-2a/credentials.json.bin
  email/18-ISbo-2a/main.py
  email/18-ISbo-2a/pattern.py
  email/18-ISbo-2a/token.pickle.bin
Labels: Sprint 10, v.0.0.0.10

#132 Реализация unit-тестов на функцию FormListWithLetters
  email/18-ISbo-2b/unit_tests/unittest_FormListWithLetters.py
Labels: Sprint 11, Testing, documentation

#133 Компоновка приватных функций Email функционала
  email/18-ISbo-2b/main_1_CheckEmail.py
  email/18-ISbo-2b/main_5_InformUsers.py
  email/18-ISbo-2b/unit_tests/unittest_SendLetters.py
  email/18-ISbo-2b/work_EmailLibrary.py
Labels: Coding, Sprint 11, add functional, realization
