Repository Students-of-the-city-of-Kostroma/trpo_automation, pull requests merged in 2020-05, with the labels that each got.

#484 Готовый проект для релиза
  LR/07/src/config/jsonSpecificationForClientRequest.xml
  LR/07/src/functional.cpp
  LR/07/src/functional.h
  LR/07/src/main.cpp
  LR/07/src/resources.qrc
  LR/07/src/src.pro
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
  LR/07/src/utils/gateway.cpp
  LR/07/src/utils/gateway.h
  LR/07/src/utils/internalexception.cpp
  LR/07/src/utils/internalexception.h
  labs.xml
Labels: Coding, add functional, release

#487 try
  .travis.yml
  LR/07/Tests/TestTcp.cpp
  LR/07/Tests/TestTcp.h
  LR/07/src/utils/internalexception.h
  LR/07/tests/test.dat
  LR/07/tests/tests.pro
Labels: release

#490 Update travis config
  .travis.yml
  .travis/18-VTbo-1b.yml
Labels: Testing

#486 настраиваем CI 2
  .travis.yml
  .travis/18-VTbo-1a.yml
  LR/07/Tests/TestTcp.cpp
  LR/07/Tests/TestTcp.h
  LR/07/Tests/Tests.pro
  LR/07/src/functional.cpp
  LR/07/src/src.pro
  LR/07/src/utils/gateway.cpp
  LR/07/src/utils/internalexception.cpp
  LR/07/src/utils/internalexception.h
  LR/07/tests/test.dat
  LR/07/tests/testgateway.cpp
  LR/07/tests/testgateway.h
  LR/07/tests/tests.pro
Labels: release

#494 little fix conflict
  README.md
Labels: release

#493 release version
  .travis.yml
  .travis/18-VTbo-1a.yml
  LR/03/Repository.xml
  LR/03/pom.xml
  LR/03/src/main/java/Selenium.java
  LR/03/src/main/java/Server.java
  LR/03/src/test/java/SeleniumTest.java
  LR/03/src/test/java/ServerTest.java
  LR/07/.gitignore
  LR/07/07.pro
  LR/07/src/config/answerStructure.xml
  LR/07/src/config/jsonSpecificationForClientRequest.xml
  LR/07/src/functional.cpp
  LR/07/src/functional.h
  LR/07/src/main.cpp
  LR/07/src/resources.qrc
  LR/07/src/src.pro
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
  LR/07/src/tcpserver.cpp
  LR/07/src/tcpserver.h
  LR/07/src/utils/gateway.cpp
  LR/07/src/utils/gateway.h
  LR/07/src/utils/internalexception.cpp
  LR/07/src/utils/internalexception.h
  LR/07/tests/test.dat
  LR/07/tests/testgateway.cpp
  LR/07/tests/testgateway.h
  LR/07/tests/tests.pro
  README.md
  labs.xml
Labels: release

#503 Реализация заполнения ФИО в класс User
  email/18-ISbo-2b/google_CheckEmail.py
Labels: Google, Sprint 8, add functional, realization

#507 Реализован метод "поиска кол-во не сданных работ"
  email/18-ISbo-2a/APIgoogle.py
Labels: Sprint 8, add functional

#506 Выполнил задачу по улучшению работы метода с Gmail API
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/pattern.py
Labels: add functional, v.0.0.0.5

#508 Валидация письма 0.0.0.5
  email/18-ISbo-2a/Validation.py
  email/18-ISbo-2a/pattern.py
Labels: Google

#517 исправил синтаксическую ошибку в pattern
  email/18-ISbo-2a/pattern.py
Labels: bug

#524 Загрузка отредактированного функционала в обновленную версию.
  email/18-ISbo-2b/main_1_google_CheckEmail.py
  email/18-ISbo-2b/main_5_send_InformUsers.py
Labels: Coding, Google, Sprint 8, add functional, bug, main, realization

#499 Написаны тесты GW
  LR/07/tests/testgateway.cpp
  LR/07/tests/testgateway.h
Labels: Testing

#537 Логирование и еще кое-что
  email/18-ISbo-2b/Loger.py
  email/18-ISbo-2b/config_Project.py
  email/18-ISbo-2b/main.py
  email/18-ISbo-2b/main_1_google_CheckEmail.py
  email/18-ISbo-2b/main_2_base_WorkWithLetters.py
  email/18-ISbo-2b/main_3_send_SetResults.py
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
  email/18-ISbo-2b/main_5_send_InformUsers.py
Labels: Critical, Sprint 8

#546 Исправил баг в переборе
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
Labels: bug

#557 Update main_4_moderate_FormAnswers.py
  email/18-ISbo-2b/main_4_moderate_FormAnswers.py
Labels: bug

#564 Исправление структуры письма
  email/18-ISbo-2b/moderate_PatternsOfLetter.py
Labels: bug

#563 Реализация проверки по конфигу answerStructure.xml
  LR/07/src/strategylab.cpp
Labels: Coding, Sprint 6

#572 Визуальный "ответ" на письмо студента
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/config.py.bak
  email/18-ISbo-2a/pattern.py
Labels: realization, v.0.0.0.8

#575 Настроен main на привычную работу.
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Example.json.bin
  email/18-ISbo-2a/config.py.bak
  email/18-ISbo-2a/config.py.bin
  email/18-ISbo-2a/credentials.json.bin
  email/18-ISbo-2a/crypto.py
  email/18-ISbo-2a/main.py
  email/18-ISbo-2a/pattern.py
  email/18-ISbo-2a/token.pickle.bin
Labels: Critical, main

#590 Разработан метод добавление пользователя в группу в журнале.
  email/18-ISbo-2a/APIgoogle.py
Labels: Sprint 9, add functional

#617 Рефакторинг main.py и доделывания основных функций.
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Example.json.bin
  email/18-ISbo-2a/config.py.bin
  email/18-ISbo-2a/credentials.json.bin
  email/18-ISbo-2a/crypto.py
  email/18-ISbo-2a/main.py
  email/18-ISbo-2a/pattern.py
  email/18-ISbo-2a/token.pickle.bin
Labels: add functional, main

#618 Pre-release.
  azure-pipelines.yml
  email/18-ISbo-2a/APIgoogle.py
  email/18-ISbo-2a/Decode.py
  email/18-ISbo-2a/Example.json.bak
  email/18-ISbo-2a/Example.json.bin
  email/18-ISbo-2a/config.py.bak
  email/18-ISbo-2a/config.py.bin
  email/18-ISbo-2a/credentials.json.bin
  email/18-ISbo-2a/crypto.py
  email/18-ISbo-2a/main.py
  email/18-ISbo-2a/pattern.py
  email/18-ISbo-2a/test_google.py
  email/18-ISbo-2a/test_google_search_tablic.py
  email/18-ISbo-2a/test_google_sheet_search_group.py
  email/18-ISbo-2a/token.pickle.bin
Labels: Critical, add functional, main

#615 Разбил строчки кода из массива на классы
  LR/07/src/strategylab.cpp
  LR/07/src/strategylab.h
Labels: Coding

#620 Написал клиент для обработки для общения с сервером
  .gitignore
  email/18-ISbo-2a/client.py
  labs.xml
Labels: Client
